function steam_ugc_get_error(resId) {
	switch(resId) { 
		case   2: return "Generic failure.";
		case   3: return "Your Steam client doesn't have a connection to the back-end.";
		case   5: return "Password/ticket is invalid.";
		case   6: return "The user is logged in elsewhere.";
		case   7: return "Protocol version is incorrect.";
		case   8: return "A parameter is incorrect.";
		case   9: return "File was not found.";
		case  10: return "Called method is busy - action not taken.";
		case  11: return "Called object was in an invalid state.";
		case  12: return "The name was invalid.";
		case  13: return "The email was invalid.";
		case  14: return "The name is not unique.";
		case  15: return "Access is denied.";
		case  16: return "Operation timed out.";
		case  17: return "The user is VAC2 banned.";
		case  18: return "Account not found.";
		case  19: return "The Steam ID was invalid.";
		case  20: return "The requested service is currently unavailable.";
		case  21: return "The user is not logged on.";
		case  22: return "Request is pending, it may be in process or waiting on third party.";
		case  23: return "Encryption or Decryption failed.";
		case  24: return "Insufficient privilege.";
		case  25: return "Too much of a good thing.";
		case  26: return "Access has been revoked (used for revoked guest passes.)";
		case  27: return "License/Guest pass the user is trying to access is expired.";
		case  28: return "Guest pass has already been redeemed by account, cannot be used again.";
		case  29: return "The request is a duplicate and the action has already occurred in the past, ignored this time.";
		case  30: return "All the games in this guest pass redemption request are already owned by the user.";
		case  31: return "IP address not found.";
		case  32: return "Failed to write change to the data store.";
		case  33: return "Failed to acquire access lock for this operation.";
		case  34: return "The logon session has been replaced.";
		case  35: return "Failed to connect.";
		case  36: return "The authentication handshake has failed.";
		case  37: return "There has been a generic IO failure.";
		case  38: return "The remote server has disconnected.";
		case  39: return "Failed to find the shopping cart requested.";
		case  40: return "A user blocked the action.";
		case  41: return "The target is ignoring sender.";
		case  42: return "Nothing matching the request found.";
		case  43: return "The account is disabled.";
		case  44: return "This service is not accepting content changes right now.";
		case  45: return "Account doesn't have value, so this feature isn't available.";
		case  46: return "Allowed to take this action, but only because requester is admin.";
		case  47: return "A Version mismatch in content transmitted within the Steam protocol.";
		case  48: return "The current CM can't service the user making a request, user should try another.";
		case  49: return "You are already logged in elsewhere, this cached credential login has failed.";
		case  50: return "The user is logged in elsewhere. (Use k_EResultLoggedInElsewhere instead!)";
		case  51: return "Long running operation has suspended/paused. (eg. content download.)";
		case  52: return "Operation has been canceled, typically by user. (eg. a content download.)";
		case  53: return "Operation canceled because data is ill formed or unrecoverable.";
		case  54: return "Operation canceled - not enough disk space.";
		case  55: return "The remote or IPC call has failed.";
		case  56: return "Password could not be verified as it's unset server side.";
		case  57: return "External account (PSN, Facebook...) is not linked to a Steam account.";
		case  58: return "PSN ticket was invalid.";
		case  59: return "External account (PSN, Facebook...) is already linked to some other account, must explicitly request to replace/delete the link first.";
		case  60: return "The sync cannot resume due to a conflict between the local and remote files.";
		case  61: return "The requested new password is not allowed.";
		case  62: return "New value is the same as the old one. This is used for secret question and answer.";
		case  63: return "Account login denied due to 2nd factor authentication failure.";
		case  64: return "The requested new password is not legal.";
		case  65: return "Account login denied due to auth code invalid.";
		case  66: return "Account login denied due to 2nd factor auth failure - and no mail has been sent.";
		case  67: return "The users hardware does not support Intel's Identity Protection Technology (IPT).";
		case  68: return "Intel's Identity Protection Technology (IPT) has failed to initialize.";
		case  69: return "Operation failed due to parental control restrictions for current user.";
		case  70: return "Facebook query returned an error.";
		case  71: return "Account login denied due to an expired auth code.";
		case  72: return "The login failed due to an IP restriction.";
		case  73: return "The current users account is currently locked for use. This is likely due to a hijacking and pending ownership verification.";
		case  74: return "The logon failed because the accounts email is not verified.";
		case  75: return "There is no URL matching the provided values.";
		case  76: return "Bad Response due to a Parse failure, missing field, etc.";
		case  77: return "The user cannot complete the action until they re-enter their password.";
		case  78: return "The value entered is outside the acceptable range.";
		case  79: return "Something happened that we didn't expect to ever happen.";
		case  80: return "The requested service has been configured to be unavailable.";
		case  81: return "The files submitted to the CEG server are not valid.";
		case  82: return "The device being used is not allowed to perform this action.";
		case  83: return "The action could not be complete because it is region restricted.";
		case  84: return "Temporary rate limit exceeded, try again later, different from k_EResultLimitExceeded which may be permanent.";
		case  85: return "Need two-factor code to login.";
		case  86: return "The thing we're trying to access has been deleted.";
		case  87: return "Login attempt failed, try to throttle response to possible attacker.";
		case  88: return "Two factor authentication (Steam Guard) code is incorrect.";
		case  89: return "The activation code for two-factor authentication (Steam Guard) didn't match.";
		case  90: return "The current account has been associated with multiple partners.";
		case  91: return "The data has not been modified.";
		case  92: return "The account does not have a mobile device associated with it.";
		case  93: return "The time presented is out of range or tolerance.";
		case  94: return "SMS code failure - no match, none pending, etc.";
		case  95: return "Too many accounts access this resource.";
		case  96: return "Too many changes to this account.";
		case  97: return "Too many changes to this phone.";
		case  98: return "Cannot refund to payment method, must use wallet.";
		case  99: return "Cannot send an email.";
		case 100: return "Can't perform operation until payment has settled.";
		case 101: return "The user needs to provide a valid captcha.";
		case 102: return "A game server login token owned by this token's owner has been banned.";
		case 103: return "Game server owner is denied for some other reason such as account locked, community ban, vac ban, missing phone, etc.";
		case 104: return "The type of thing we were requested to act on is invalid.";
		case 105: return "The IP address has been banned from taking this action.";
		case 106: return "This Game Server Login Token (GSLT) has expired from disuse; it can be reset for use.";
		case 107: return "user doesn't have enough wallet funds to complete the action";
		case 108: return "There are too many of this thing pending already";
	} 
	
	return "";
}